{
  "message": "success",
  "data": {
    "user": {
      "message": "",
      "member_type": 4,
      "new_user": false,
      "session_token": "b2d04b91-f9fe-423b-be9b-e5eeaa2886cd",
      "is_demographics_updated": 1,
      "user_id": 6760400,
      "userId": 6760400,
      "entity_id": 6760400,
      "is_trial_expired": false,
      "code": 11,
      "device_uid": "e57967450e8425dc",
      "device_os": "android",
      "currency": "USD",
      "device_model": "samsung%20SM-G935F",
      "country_of_residence": "BH",
      "nationality": "PK",
      "user_creation_date": "2019-01-22 14:51:02",
      "created_at": "2019-01-22 14:51:02",
      "gender": "male",
      "last_name": "ali",
      "lastname": "ali",
      "about_me": "",
      "email": "kashif1234767@gmail.com",
      "first_name": "kashif",
      "affiliate_code": "",
      "savings": 715,
      "profile_image": "https://entertainer-profile-images.s3.amazonaws.com/6760400_tPNQTSrlFcqN3Lbw2TpRwaYr9WnTgzlD.jpg",
      "onboarding_startdate": "2019-09-02 09:29:32",
      "income_bracket": "",
      "using_trial": 0,
      "education_level": null,
      "default_currency": 45,
      "lifestyle_preference": "",
      "updated_at": "2020-10-20 16:32:22",
      "onboarding_redemptions_count": 0,
      "work_address": "",
      "home_address": "",
      "occupation_level": "",
      "accepted_terms": 1,
      "is_active": 1,
      "onboarding_status": 2,
      "push_notifications": 1,
      "date_of_birth": "15/01/1987",
      "is_phone_verified": 0,
      "verification_state": 0,
      "city_of_residence": "",
      "age_bracket": "",
      "membership_code": "M19PK067604001",
      "mobile_phone": "",
      "marital_status": null,
      "do_not_email": "0",
      "third_do_not_email": "0",
      "used_trial_membership": 1,
      "membership_expiration_date": "2021-01-02 00:00:00",
      "country": "BH",
      "is_secondary": 0,
      "is_primary": 0,
      "password_update_require": false
    }
  },
  "success": true,
  "code": 0,
  "cmd": "/et_rs_prd/web/v70/sessions?",
  "http_response": 200
}
